x-backend-templates:
  app: &app
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: csouzadocker/rinha-backend-2025-puro:0.0.1
    depends_on:
      backend-db:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "117.50MB"

  app-env: &app-env
    PAYMENT_PROCESSOR_WORKERS: "4"
    datasource-class-name: "org.postgresql.Driver"
    datasource-maximum-pool-size: "4"
    datasource-minimum-idle: "4"
    datasource-password: "rinha"
    datasource-timeout: "2000"
    datasource-url: "jdbc:postgresql://postgres:5432/rinha"
    datasource-username: "rinha"
    payment-processor-default-url: "http://payment-processor-default:8080"
    payment-processor-fallback-url: "http://payment-processor-fallback:8080"
    server-port: "8080"
    server-io-threads: "2"
    server-worker-threads: "4"
    thread-pool-size: "10"
    thread-queue-size: "500"
#    warmup: "false"
#    warmup_rounds: "10000"
    JAVA_OPTS: >
      -Xmx100m
      -Xms100m
      -XX:MaxMetaspaceSize=40m
      -XX:MaxGCPauseMillis=200
      -Xss512k
      -XX:+UseG1GC
      -XX:+UseCompressedOops
      -XX:+UseCompressedClassPointers
      -XX:+AlwaysPreTouch
      -Xbatch
      -XX:+UnlockExperimentalVMOptions
      -XX:+UnlockDiagnosticVMOptions
      -XX:+UseFastUnorderedTimeStamps
      -XX:+ExitOnOutOfMemoryError
      -XX:+TieredCompilation
      -XX:TieredStopAtLevel=1
      -XX:CompileThreshold=500
      -XX:+HeapDumpOnOutOfMemoryError
    #    -XX:+UseNUMA \
    #    -XX:+PrintCompilation
    #    -XX:+PrintTieredEvents
    #    -XX:+PrintCodeCache
    #    -XX:+PrintInlining

services:
  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  app1:
    <<: *app
    container_name: backend-api1
    hostname: app1
    environment:
      <<: *app-env
      warmup_instance: "app2"

  app2:
    <<: *app
    container_name: backend-api2
    hostname: app2
    environment:
      <<: *app-env
      warmup_instance: "app1"

  backend-db:
    image: postgres:17-alpine
    container_name: backend-db
    hostname: postgres
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    volumes:
      - ./init.sql/init-backend-db.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./init.sql/init-config.sh:/docker-entrypoint-initdb.d/init-config.sh
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rinha -d rinha" ]
      interval: 3s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
