x-backend-templates:
  app: &app
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: ccs1201/rinha-backend-2025-puro:latest
    depends_on:
      - backend-db
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "117.50MB"

  app-env: &app-env
    PAYMENT_PROCESSOR_WORKERS: "25"
    datasource-class-name: "org.postgresql.Driver"
    datasource-maximum-pool-size: "10"
    datasource-minimum-idle: "10"
    datasource-password: "rinha"
    datasource-timeout: "2000"
    datasource-url: "jdbc:postgresql://postgres:5432/rinha"
    datasource-username: "rinha"
    payment-processor-default-url: "http://payment-processor-default:8080"
    payment-processor-fallback-url: "http://payment-processor-fallback:8080"
    server-port: "8080"
    server-io-threads: "2"
    server-worker-threads: "8"
    thread-pool-size: "10"
    thread-queue-size: "100"
    warmup: "true"
    warmup_rounds: "10000"
    JAVA_OPTS: "-Xmx95m -Xms95m -XX:MaxMetaspaceSize=50m -XX:+UseG1GC"

services:
  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  app1:
    <<: *app
    container_name: backend-api1
    hostname: app1
    environment:
      <<: *app-env
      warmup_instance: "app2"

  app2:
    <<: *app
    container_name: backend-api2
    hostname: app2
    environment:
      <<: *app-env
      warmup_instance: "app1"

  backend-db:
    image: postgres:17-alpine
    container_name: backend-db
    hostname: postgres
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    volumes:
      - ./init.sql/init-backend-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init.sql/init-config.sh:/docker-entrypoint-initdb.d/init-config.sh
    ports:
      - "5432:5432"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
